all:
	cd gcp-access-token && make -f Makefile.linux
	cd gcp-sign && make -f Makefile.linux
	cd gcp-verify && make -f Makefile.linux

clean:
	cd gcp-access-token && make -f Makefile.linux clean
	cd gcp-sign && make -f Makefile.linux clean
	cd gcp-verify && make -f Makefile.linux clean
